### ISSUE TITLE
Don't put your VATSIM password on Github

### ISSUE THREAD

**Issue by cpawley** [andrebrito16/BRZ-TOP-SKY-PACK#1]
https://github.com/andrebrito16/BRZ-TOP-SKY-PACK/blob/f00a7e667d843674badb8088e1a18f5404433c7a/BRZ-TopSky/FIR%20BRASILIA/TMA%20Brasilia/Controle%20Brasilia/Controle%20Brasilia.prf#L20

**Comment by andrebrito16** [comment]
Hi, I changed password few months ago. Thanks in advance!
